### ISSUE TITLE
services start command missing

### ISSUE THREAD

**Issue by dpatil-fw** [FIWARE/tutorials.Linked-Data#18]
Under https://github.com/FIWARE/tutorials.Linked-Data#start-up

./services start 

is missing in the steps. Kindly add.

**Comment by jason-fox** [comment]
Under https://github.com/FIWARE/tutorials.Linked-Data#start-up - the following is already defined:

```console
git clone https://github.com/FIWARE/tutorials.Linked-Data.git
cd tutorials.Linked-Data
git checkout NGSI-v2

./services orion|scorpio
```

This defines which context broker you want to start the tutorial with - either using **Orion-LD** or **Scorpio**.

The [NGSI-LD for NGSI-v2 developers](https://fiware-tutorials.readthedocs.io/en/latest/linked-data/index.html) tutorials are a little different to the other NGSI-v2 tutorials since under NGSI-LD there is now a choice of broker to use. The [NGSI-LD first tutorials](https://ngsi-ld-tutorials.readthedocs.io/) do the same thing. You need to chose between  **Orion-LD**, **Scorpio** or **Stellio**

For an NGSI-LD tutorial, running

```console
 ./services start
```

Results in an error message:

```text
Command not Found.
usage: services [create|orion|scorpio|stop]
```

Which should be clear enough. Or am I missing something?

**Comment by dpatil-fw** [comment]
I am sorry, I did not try out the command but was just reading through the tutorials prior. 

Checking the 'services' link given here: https://github.com/FIWARE/tutorials.Linked-Data#start-up

'All services can be initialised from the command-line by running the [services](https://github.com/FIWARE/tutorials.Linked-Data/blob/NGSI-v2/services) Bash script'

In the line above, would be better if the 'services' url link can be changed from 
[https://github.com/FIWARE/tutorials.Linked-Data/blob/NGSI-v2/services](https://github.com/FIWARE/tutorials.Linked-Data/blob/NGSI-v2/services)
to
[https://github.com/FIWARE/tutorials.Linked-Data/blob/master/services](https://github.com/FIWARE/tutorials.Linked-Data/blob/master/services)

**Comment by dpatil-fw** [comment]
Please ignore the issue raised, all is good. I am closing it.
