### ISSUE TITLE
Posman Collection @context links broken

### ISSUE THREAD

**Issue by MNXOnline** [FIWARE/tutorials.Linked-Data#21]
The examples on the Postman Collection point to broken @context links.
The example in the README file, at lines 435-438 point at:
```
"@context": [
        "https://fiware.github.io/data-models/context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld"
    ]
```
and in the Postman Collection Request "Creating your first Data Entity" points at:
```
    "@context": [
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
        "https://schema.lab.fiware.org/ld/fiware-datamodels-context.jsonld"
    ]
```
P.S.: @jason-fox "https://uri.fiware.org/ns/data-models" gives a 404 and inside "https://fiware.github.io/data-models/context.jsonld" there are dozens of entities defined with it. The "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld" has also got links to 404 files such as "https://uri.etsi.org/ngsi-ld/default-context/"

**Comment by jason-fox** [comment]
On closer inspection, the `@context` files do exist, but the question is about the IRIs within the `@context` files not resolving as URLs. This is actually not a requirement of JSON-LD. A further discussion can be found in an issue raised in the [Smart Data Models repo](https://github.com/smart-data-models/data-models/issues/17)

Since this isn't obvious, and at first glance the  `https://uri.fiware.org/ns/data-models` IRIs appear to be URLs, what is really needed is a clarification to be added to the tutorial `README`

**Comment by jason-fox** [comment]
Documentation updated see: https://fiware-tutorials.readthedocs.io/en/latest/linked-data/index.html#context-terms-are-iris-not-urls
